// example/features/Vue/DemoComponent.vue
<template>
    <div>
        <h1>{{ heading }}</h1>
        <p>{{ active ? 'active' : 'not-active' }}</p>
        <button @click="active = !active" type="button">toggle active</button>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
    props: {
        heading: String,
        active: Boolean,
    },
    data() {
        return {
            active: false,
        };
    },
});
</script>

// example/features/DemoComponent/DemoComponent.tsx
import { useState } from 'react';

interface IDemoComponent {
    heading: string;
}

const DemoComponent = (props: IDemoComponent) => {
    const [active, setActive] = useState(false);

    return (
        <div>
            <h1>{props.heading}</h1>
            <p>{active ? 'active' : 'not active'}</p>
            <button onClick={() => setActive(!active)} type="button">
                toggle active
            </button>
        </div>
    );
};

export default DemoComponent;
